[package]
name = "postgres"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
aes-gcm.workspace = true
agent = { path = "../../modules/agent" }
argon2 = { workspace = true, features = ["std"] }
async-trait.workspace = true
aws-lc-rs.workspace = true
base64.workspace = true
chrono.workspace = true
contracts = { path = "../../core/contracts" }
dashmap.workspace = true
domain = { path = "../../core/domain" }
function-runtime = { path = "../function-runtime" }
hex.workspace = true
kernel = { path = "../../core/kernel" }
moka.workspace = true
parking_lot.workspace = true
prometheus.workspace = true
rand.workspace = true
rcgen.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
settings = { path = "../../core/settings" }
sha2.workspace = true
signals = { path = "../../support/signals" }
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
default = []
js-runtime = ["function-runtime/js-runtime"]
