import axios from 'axios';

import type { IngestResult } from '@/api/ingestion';
import * as queryApi from '@/api/query';
import { toApiError } from '@/lib/http';

export type RumPlatform = 'browser' | 'flutter' | 'android' | 'ios';

export interface TestRumErrorRequest {
  token: string;
  applicationId: string;
  platform: RumPlatform;
  service: string;
}

export interface RumReceiptSummary {
  rows: number;
  lastReceivedAtMicros: number | null;
}

export async function sendTestError(
  request: TestRumErrorRequest,
): Promise<IngestResult> {
  const platform = request.platform === 'browser' ? 'web' : request.platform;
  const event = {
    application: request.applicationId,
    service: request.service,
    version: 'datasource-test',
    platform,
    sdk_name: `molesignal-${request.platform}-datasource`,
    timestamp: Date.now() * 1000,
    session_id: crypto.randomUUID(),
    level: 'error',
    message: `MoleSignal ${request.platform} RUM datasource test error`,
    error: {
      type: 'DatasourceTestError',
      message: 'Test error generated by the MoleSignal datasource guide',
      stack: [
        {
          file: 'datasource-test.js',
          function: 'sendTestError',
          line: 1,
          column: 1,
        },
      ],
    },
  };
  const { data } = await axios.post<IngestResult>('/api/v1/rum/errors', [event], {
    headers: { Authorization: `Bearer ${request.token}` },
  });
  return data;
}

export async function recentErrorSummary(params: {
  orgId: string;
  applicationId: string;
}): Promise<RumReceiptSummary> {
  const now = Date.now() * 1000;
  const application = params.applicationId.replaceAll("'", "''");
  try {
    const result = await queryApi.runQuery({
      org_id: params.orgId,
      language: 'sql',
      statement:
        `SELECT COUNT(*) AS rows, MAX(CAST(_timestamp AS BIGINT)) AS last_received_at_micros ` +
        `FROM "rum_errors" WHERE "application" = '${application}'`,
      time_range: { start: now - 60 * 60 * 1_000_000, end: now },
      stream: { name: 'rum_errors', stream_type: 'logs' },
      limit: 1,
    });
    const row = result.rows[0] ?? [];
    return {
      rows: numeric(row[0]) ?? 0,
      lastReceivedAtMicros: numeric(row[1]),
    };
  } catch (error) {
    const apiError = toApiError(error);
    if (/stream not found|unknown stream/i.test(apiError.message)) {
      return { rows: 0, lastReceivedAtMicros: null };
    }
    throw error;
  }
}

function numeric(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string') {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) return parsed;
  }
  return null;
}
