// @generated
// This file is @generated by prost-build.
/// 镜像 domain::ingestion::IngestBatch 的字段集。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PushRequest {
    #[prost(string, tag="1")]
    pub batch_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub stream: ::prost::alloc::string::String,
    #[prost(enumeration="StreamType", tag="4")]
    pub stream_type: i32,
    /// 客户端原始 NDJSON / JSON array / OTLP payload 的 bytes，由 ingester 解析
    #[prost(bytes="bytes", tag="5")]
    pub payload: ::prost::bytes::Bytes,
    #[prost(int64, tag="6")]
    pub received_at_micros: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PushResponse {
    #[prost(uint32, tag="1")]
    pub accepted: u32,
    #[prost(uint32, tag="2")]
    pub rejected: u32,
    #[prost(message, repeated, tag="3")]
    pub errors: ::prost::alloc::vec::Vec<IngestError>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IngestError {
    #[prost(uint32, tag="1")]
    pub index: u32,
    #[prost(string, tag="2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StreamType {
    Unspecified = 0,
    Logs = 1,
    Metrics = 2,
    Traces = 3,
    Profiles = 4,
}
impl StreamType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STREAM_TYPE_UNSPECIFIED",
            Self::Logs => "STREAM_TYPE_LOGS",
            Self::Metrics => "STREAM_TYPE_METRICS",
            Self::Traces => "STREAM_TYPE_TRACES",
            Self::Profiles => "STREAM_TYPE_PROFILES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STREAM_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "STREAM_TYPE_LOGS" => Some(Self::Logs),
            "STREAM_TYPE_METRICS" => Some(Self::Metrics),
            "STREAM_TYPE_TRACES" => Some(Self::Traces),
            "STREAM_TYPE_PROFILES" => Some(Self::Profiles),
            _ => None,
        }
    }
}
include!("ingest.v1.tonic.rs");
// @@protoc_insertion_point(module)