#!/usr/bin/env tsx
/**
 * Render `web/src/keyboard/bindings.ts::GLOBAL_KEYMAP` into a Markdown file
 * (`docs/web/keyboard.md`). Run via:
 *
 *     pnpm -C web dump:keymap
 *
 * CI re-runs this and `git diff --exit-code docs/web/keyboard.md` to catch
 * drift between the code-of-truth (bindings.ts) and the rendered doc.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { GLOBAL_KEYMAP } from '../src/keyboard/bindings';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const out = path.resolve(__dirname, '../../docs/web/keyboard.md');

const CATEGORY_LABEL: Record<string, string> = {
  general: 'General',
  navigation: 'Navigation',
  time: 'Time',
  investigation: 'Investigation stack',
  editing: 'Editing',
};

function prettyKey(combo: string): string {
  return combo
    .split(' ')
    .map((step) =>
      step
        .replace('mod', '⌘')
        .replace('shift', '⇧')
        .replace('alt', '⌥')
        .replace('esc', 'Esc')
        .replace('enter', 'Enter'),
    )
    .map((step) => '`' + step + '`')
    .join(' ');
}

function render(): string {
  const byCat: Record<string, typeof GLOBAL_KEYMAP> = {};
  for (const b of GLOBAL_KEYMAP) {
    (byCat[b.category] ??= []).push(b);
  }
  const lines: string[] = [
    '# Keyboard reference',
    '',
    '> Generated by `pnpm -C web dump:keymap` from `web/src/keyboard/bindings.ts`.',
    '> Do not edit by hand — CI verifies this is in sync with the source.',
    '',
  ];

  for (const [cat, items] of Object.entries(byCat)) {
    lines.push(`## ${CATEGORY_LABEL[cat] ?? cat}`);
    lines.push('');
    lines.push('| Keys | Action |');
    lines.push('| ---- | ------ |');
    for (const b of items) {
      lines.push(`| ${prettyKey(b.keys)} | ${b.description} |`);
    }
    lines.push('');
  }

  lines.push('## Scope-specific bindings');
  lines.push('');
  lines.push(
    'Scope bindings are registered at component mount time via `useBindings(scope, [...])` and shadow the global keymap. The bindings below are surfaced through the `mod+/` help overlay when the corresponding scope is on top of the stack.',
  );
  lines.push('');
  lines.push('| Scope | Source |');
  lines.push('| ----- | ------ |');
  lines.push('| `palette` | `web/src/palette/CommandPalette.tsx` |');
  lines.push('| `drawer` | `web/src/investigation/DrawerFrame.tsx` |');
  lines.push('| `chart-brush` | `web/src/viz/timeseries/brush.ts` |');
  lines.push('| `editor` | (future SQL/PromQL frame) |');
  lines.push('| `help-overlay` | `web/src/keyboard/HelpOverlay.tsx` |');
  lines.push('');
  return lines.join('\n');
}

mkdirSync(path.dirname(out), { recursive: true });
writeFileSync(out, render(), 'utf8');
console.log(`wrote ${out}`);
