// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 MoleSignal Authors

import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(scriptDirectory, '..');
const repositoryRoot = resolve(webRoot, '..');
const canonicalRoot = resolve(repositoryRoot, 'contracts/dashboard');
const generatedRoot = resolve(
  webRoot,
  'src/dashboard-engine/contracts/generated',
);
const checkOnly = process.argv.includes('--check');

const canonicalAssets = [
  'model/v2.schema.json',
  'authoring/v1.schema.json',
  'visualizations/v1.json',
  ...(await jsonFiles(resolve(canonicalRoot, 'fixtures'))).map((path) =>
    relative(canonicalRoot, path),
  ),
].sort();

const assetContents = new Map<string, string>();
for (const asset of canonicalAssets) {
  assetContents.set(asset, await readFile(resolve(canonicalRoot, asset), 'utf8'));
}

const schemaModule = generatedSchemaModule(assetContents);
const expectedFiles = new Map<string, string>([
  ...assetContents,
  ['schemas.ts', schemaModule],
]);

const drift: string[] = [];
for (const [asset, expected] of expectedFiles) {
  const target = resolve(generatedRoot, asset);
  if (checkOnly) {
    const actual = await readOptional(target);
    if (actual !== expected) drift.push(asset);
    continue;
  }
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, expected, 'utf8');
}

if (checkOnly && drift.length > 0) {
  throw new Error(
    `Dashboard contract drift detected: ${drift.join(', ')}. Run pnpm -C web dashboard-contracts:sync.`,
  );
}

async function jsonFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await jsonFiles(path)));
    else if (entry.isFile() && entry.name.endsWith('.json')) files.push(path);
  }
  return files.sort();
}

async function readOptional(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if (
      typeof error === 'object' &&
      error !== null &&
      'code' in error &&
      error.code === 'ENOENT'
    ) {
      return undefined;
    }
    throw error;
  }
}

function generatedSchemaModule(contents: Map<string, string>): string {
  const model = parseJson(contents, 'model/v2.schema.json');
  const authoring = parseJson(contents, 'authoring/v1.schema.json');
  const visualizations = parseJson(contents, 'visualizations/v1.json');
  return `// @generated by scripts/sync-dashboard-contracts.ts; DO NOT EDIT.\n\n` +
    `export const dashboardModelV2Schema = ${JSON.stringify(model, null, 2)} as const;\n\n` +
    `export const dashboardAuthoringV1Schema = ${JSON.stringify(authoring, null, 2)} as const;\n\n` +
    `export const dashboardVisualizationsV1 = ${JSON.stringify(visualizations, null, 2)} as const;\n\n` +
    `export const dashboardContractHashes = ${JSON.stringify(
      {
        dashboardModelV2: canonicalHash(model),
        dashboardAuthoringV1: canonicalHash(authoring),
        dashboardVisualizationsV1: canonicalHash(visualizations),
      },
      null,
      2,
    )} as const;\n`;
}

function parseJson(contents: Map<string, string>, path: string): unknown {
  const content = contents.get(path);
  if (!content) throw new Error(`Missing canonical Dashboard contract: ${path}`);
  return JSON.parse(content) as unknown;
}

function canonicalHash(value: unknown): string {
  return createHash('sha256')
    .update(JSON.stringify(sortKeys(value)))
    .digest('hex');
}

function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (typeof value !== 'object' || value === null) return value;
  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, nested]) => [key, sortKeys(nested)]),
  );
}
