[package]
name = "domain-management"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
kernel = { path = "../../core/kernel" }
once_cell.workspace = true
regex.workspace = true
serde.workspace = true
