// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Profile {
    /// A description of the samples associated with each Sample.value.
    #[prost(message, repeated, tag="1")]
    pub sample_type: ::prost::alloc::vec::Vec<ValueType>,
    /// The set of samples recorded in this profile.
    #[prost(message, repeated, tag="2")]
    pub sample: ::prost::alloc::vec::Vec<Sample>,
    /// Mapping from address ranges to the image/binary/library mapped into it.
    #[prost(message, repeated, tag="3")]
    pub mapping: ::prost::alloc::vec::Vec<Mapping>,
    /// Locations referenced by samples.
    #[prost(message, repeated, tag="4")]
    pub location: ::prost::alloc::vec::Vec<Location>,
    /// Functions referenced by locations.
    #[prost(message, repeated, tag="5")]
    pub function: ::prost::alloc::vec::Vec<Function>,
    /// A common table for strings referenced by various messages.
    /// string_table\[0\] must always be "".
    #[prost(string, repeated, tag="6")]
    pub string_table: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// frames with Function.function_name fully matching the following
    /// regexp will be dropped from the samples, along with their successors.
    #[prost(int64, tag="7")]
    pub drop_frames: i64,
    /// frames with Function.function_name fully matching the following
    /// regexp will be kept, even if it matches drop_frames.
    #[prost(int64, tag="8")]
    pub keep_frames: i64,
    /// Time of collection (UTC) represented as nanoseconds past the epoch.
    #[prost(int64, tag="9")]
    pub time_nanos: i64,
    /// Duration of the profile, if a duration makes sense.
    #[prost(int64, tag="10")]
    pub duration_nanos: i64,
    /// The kind of events between sampled occurrences.
    #[prost(message, optional, tag="11")]
    pub period_type: ::core::option::Option<ValueType>,
    /// The number of events between sampled occurrences.
    #[prost(int64, tag="12")]
    pub period: i64,
    /// Free-form text associated with the profile (indices into string_table).
    #[prost(int64, repeated, tag="13")]
    pub comment: ::prost::alloc::vec::Vec<i64>,
    /// Index into the string table of the type of the preferred sample value.
    #[prost(int64, tag="14")]
    pub default_sample_type: i64,
    /// Documentation link for this profile type (index into string_table).
    #[prost(int64, tag="15")]
    pub doc_url: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValueType {
    /// index into string_table
    #[prost(int64, tag="1")]
    pub r#type: i64,
    /// index into string_table
    #[prost(int64, tag="2")]
    pub unit: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sample {
    /// The ids recorded here correspond to a Profile.location.id.
    /// The leaf is at location_id\[0\].
    #[prost(uint64, repeated, tag="1")]
    pub location_id: ::prost::alloc::vec::Vec<u64>,
    /// The type and unit of each value is defined by the corresponding
    /// entry in Profile.sample_type.
    #[prost(int64, repeated, tag="2")]
    pub value: ::prost::alloc::vec::Vec<i64>,
    /// label includes additional context for this sample.
    #[prost(message, repeated, tag="3")]
    pub label: ::prost::alloc::vec::Vec<Label>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Label {
    /// index into string_table
    #[prost(int64, tag="1")]
    pub key: i64,
    /// At most one of the following must be present.
    ///
    /// index into string_table
    #[prost(int64, tag="2")]
    pub str: i64,
    #[prost(int64, tag="3")]
    pub num: i64,
    /// Should only be present when num is present.
    ///
    /// index into string_table
    #[prost(int64, tag="4")]
    pub num_unit: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Mapping {
    #[prost(uint64, tag="1")]
    pub id: u64,
    #[prost(uint64, tag="2")]
    pub memory_start: u64,
    #[prost(uint64, tag="3")]
    pub memory_limit: u64,
    #[prost(uint64, tag="4")]
    pub file_offset: u64,
    /// index into string_table
    #[prost(int64, tag="5")]
    pub filename: i64,
    /// index into string_table
    #[prost(int64, tag="6")]
    pub build_id: i64,
    #[prost(bool, tag="7")]
    pub has_functions: bool,
    #[prost(bool, tag="8")]
    pub has_filenames: bool,
    #[prost(bool, tag="9")]
    pub has_line_numbers: bool,
    #[prost(bool, tag="10")]
    pub has_inline_frames: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Location {
    #[prost(uint64, tag="1")]
    pub id: u64,
    #[prost(uint64, tag="2")]
    pub mapping_id: u64,
    #[prost(uint64, tag="3")]
    pub address: u64,
    /// Multiple line indicates this location has inlined functions,
    /// where the last entry represents the caller into which the
    /// preceding entries were inlined.
    #[prost(message, repeated, tag="4")]
    pub line: ::prost::alloc::vec::Vec<Line>,
    #[prost(bool, tag="5")]
    pub is_folded: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Line {
    #[prost(uint64, tag="1")]
    pub function_id: u64,
    #[prost(int64, tag="2")]
    pub line: i64,
    #[prost(int64, tag="3")]
    pub column: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Function {
    #[prost(uint64, tag="1")]
    pub id: u64,
    /// index into string_table
    #[prost(int64, tag="2")]
    pub name: i64,
    /// index into string_table
    #[prost(int64, tag="3")]
    pub system_name: i64,
    /// index into string_table
    #[prost(int64, tag="4")]
    pub filename: i64,
    #[prost(int64, tag="5")]
    pub start_line: i64,
}
// @@protoc_insertion_point(module)
