[package]
name = "service-graph"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
dashmap.workspace = true
domain = { path = "../../core/domain" }
kernel = { path = "../../core/kernel" }
parking_lot.workspace = true
postgres = { path = "../postgres" }
serde.workspace = true
signals = { path = "../../support/signals" }
sqlx.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
