import {
  AppWindow,
  Bug,
  FileCode2,
  Gauge,
  MonitorPlay,
  MonitorSmartphone,
  PanelsTopLeft,
  Settings,
  Users,
} from 'lucide-react';

import type { ProductRouteMeta } from '../ia';

const RUM_ACCESS = {
  edition: 'any',
  owner: 'rum',
  emptyStateStrategy: 'query-first',
  group: 'investigate',
} as const;

const rumCrumb = { labelKey: 'rum', to: '/rum/overview' } as const;

export const RUM_PRODUCT_ROUTES = [
  {
    ...RUM_ACCESS,
    id: 'rum',
    path: '/rum',
    labelKey: 'rum',
    icon: MonitorSmartphone,
    nav: true,
  },
  {
    ...RUM_ACCESS,
    id: 'rum.overview',
    path: '/rum/overview',
    labelKey: 'breadcrumbs.rum_overview',
    icon: Gauge,
    breadcrumbs: [rumCrumb, { labelKey: 'breadcrumbs.rum_overview' }],
    backTo: '/rum',
  },
  {
    ...RUM_ACCESS,
    id: 'rum.applications',
    path: '/rum/applications',
    labelKey: 'breadcrumbs.rum_applications',
    icon: AppWindow,
    breadcrumbs: [rumCrumb, { labelKey: 'breadcrumbs.rum_applications' }],
    backTo: '/rum/overview',
  },
  {
    ...RUM_ACCESS,
    id: 'rum.sessions',
    path: '/rum/sessions',
    labelKey: 'rum_sessions',
    icon: Users,
    breadcrumbs: [rumCrumb, { labelKey: 'rum_sessions' }],
    backTo: '/rum/overview',
  },
  {
    ...RUM_ACCESS,
    id: 'rum.session',
    path: '/rum/sessions/view/:id',
    labelKey: 'breadcrumbs.rum_session',
    icon: MonitorPlay,
    breadcrumbs: [
      rumCrumb,
      { labelKey: 'rum_sessions', to: '/rum/sessions' },
      { labelKey: 'breadcrumbs.rum_session' },
    ],
    backTo: '/rum/sessions',
  },
  {
    ...RUM_ACCESS,
    id: 'rum.pages',
    path: '/rum/pages',
    labelKey: 'breadcrumbs.rum_pages',
    icon: PanelsTopLeft,
    breadcrumbs: [rumCrumb, { labelKey: 'breadcrumbs.rum_pages' }],
    backTo: '/rum/overview',
  },
  {
    ...RUM_ACCESS,
    id: 'rum.errors',
    path: '/rum/errors',
    labelKey: 'rum_errors',
    icon: Bug,
    breadcrumbs: [rumCrumb, { labelKey: 'rum_errors' }],
    backTo: '/rum/overview',
  },
  {
    ...RUM_ACCESS,
    id: 'rum.error',
    path: '/rum/errors/view/:id',
    labelKey: 'breadcrumbs.rum_error',
    icon: Bug,
    breadcrumbs: [
      rumCrumb,
      { labelKey: 'rum_errors', to: '/rum/errors' },
      { labelKey: 'breadcrumbs.rum_error' },
    ],
    backTo: '/rum/errors',
  },
  {
    ...RUM_ACCESS,
    id: 'rum.performance',
    path: '/rum/performance/overview',
    labelKey: 'rum_performance',
    icon: Gauge,
    breadcrumbs: [rumCrumb, { labelKey: 'rum_performance' }],
    backTo: '/rum/overview',
  },
  {
    ...RUM_ACCESS,
    id: 'rum.session.replay',
    path: '/rum/session-replay',
    labelKey: 'breadcrumbs.rum_session_replay',
    icon: MonitorPlay,
    breadcrumbs: [rumCrumb, { labelKey: 'breadcrumbs.rum_session_replay' }],
    backTo: '/rum/overview',
  },
  {
    ...RUM_ACCESS,
    id: 'rum.settings',
    path: '/rum/settings/:section',
    labelKey: 'breadcrumbs.rum_settings',
    icon: Settings,
    breadcrumbs: [rumCrumb, { labelKey: 'breadcrumbs.rum_settings' }],
    backTo: '/rum/overview',
  },
  {
    ...RUM_ACCESS,
    id: 'rum.source.maps',
    path: '/rum/settings/source-maps',
    labelKey: 'rum_source_maps',
    icon: FileCode2,
    breadcrumbs: [
      rumCrumb,
      { labelKey: 'breadcrumbs.rum_settings', to: '/rum/settings/sdk' },
      { labelKey: 'rum_source_maps' },
    ],
    backTo: '/rum/settings/sdk',
  },
  {
    ...RUM_ACCESS,
    id: 'rum.upload.source.maps',
    path: '/rum/settings/source-maps/upload',
    labelKey: 'breadcrumbs.rum_upload_source_maps',
    icon: FileCode2,
    emptyStateStrategy: 'create-first',
    breadcrumbs: [
      rumCrumb,
      { labelKey: 'breadcrumbs.rum_settings', to: '/rum/settings/sdk' },
      { labelKey: 'rum_source_maps', to: '/rum/settings/source-maps' },
      { labelKey: 'breadcrumbs.rum_upload_source_maps' },
    ],
    backTo: '/rum/settings/source-maps',
  },
] as const satisfies readonly ProductRouteMeta[];
