// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitTraceCandidateRequest {
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    /// system_self_trace=true 时 stream 必须为空，owner 将其写入 _sys/_molesignal；
    /// 否则 stream 是租户 Trace stream。
    #[prost(string, tag="2")]
    pub stream: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub system_self_trace: bool,
    /// 完整且有界的 CanonicalSpan JSON。Resource/Scope 由 producer 生成，owner 不重写。
    #[prost(bytes="bytes", tag="4")]
    pub canonical_span_json: ::prost::bytes::Bytes,
    #[prost(enumeration="TraceForceKeep", tag="5")]
    pub force_keep: i32,
    #[prost(string, tag="6")]
    pub producer_node_id: ::prost::alloc::string::String,
    #[prost(int64, tag="7")]
    pub produced_at_micros: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitTraceCandidateResponse {
    #[prost(enumeration="TraceCandidateDisposition", tag="1")]
    pub disposition: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeInfo {
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// host:port，用于 grpc / arrow flight
    #[prost(string, tag="2")]
    pub advertise_addr: ::prost::alloc::string::String,
    #[prost(enumeration="NodeRole", repeated, tag="3")]
    pub roles: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, tag="4")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeartbeatRequest {
    #[prost(message, optional, tag="1")]
    pub node: ::core::option::Option<NodeInfo>,
    #[prost(int64, tag="2")]
    pub ts_micros: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeartbeatResponse {
    #[prost(int64, tag="1")]
    pub server_ts_micros: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListNodesRequest {
    /// 可选过滤：只列指定角色的节点。空表示返回全部。
    #[prost(enumeration="NodeRole", repeated, tag="1")]
    pub roles: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListNodesResponse {
    #[prost(message, repeated, tag="1")]
    pub nodes: ::prost::alloc::vec::Vec<NodeInfo>,
}
/// 集群引用（gossip 仅传播这三项；token / org 映射绝不出网）。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClusterRef {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub advertise_addr: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GossipRequest {
    #[prost(message, repeated, tag="1")]
    pub known: ::prost::alloc::vec::Vec<ClusterRef>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GossipResponse {
    #[prost(message, repeated, tag="1")]
    pub known: ::prost::alloc::vec::Vec<ClusterRef>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelQueryRequest {
    #[prost(string, tag="1")]
    pub federation_query_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelQueryResponse {
    /// 本节点是否找到并取消了该 id 的在跑查询。
    #[prost(bool, tag="1")]
    pub cancelled: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PushEventsRequest {
    /// 发源集群 id（接收端据此查 org 映射 / 投递游标）。
    #[prost(string, tag="1")]
    pub source_cluster_id: ::prost::alloc::string::String,
    /// 每条是一个序列化的 CloudEvent（JSON bytes）。
    #[prost(bytes="bytes", repeated, tag="2")]
    pub events_json: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PushEventsResponse {
    /// 已应用（或幂等跳过）的事件 id。
    #[prost(string, repeated, tag="1")]
    pub accepted_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 终态拒绝（未映射 org / 鉴权失败 / 解析失败 —— 重试也不会成功）的事件 id。
    #[prost(string, repeated, tag="2")]
    pub rejected_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 瞬时失败（DB 抖动等）应**重试**的事件 id：发送端不推进游标过这些事件，下 tick 重投。
    #[prost(string, repeated, tag="3")]
    pub retry_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TraceForceKeep {
    Unspecified = 0,
    TrustedInternal = 1,
    DebugToken = 2,
}
impl TraceForceKeep {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TRACE_FORCE_KEEP_UNSPECIFIED",
            Self::TrustedInternal => "TRACE_FORCE_KEEP_TRUSTED_INTERNAL",
            Self::DebugToken => "TRACE_FORCE_KEEP_DEBUG_TOKEN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRACE_FORCE_KEEP_UNSPECIFIED" => Some(Self::Unspecified),
            "TRACE_FORCE_KEEP_TRUSTED_INTERNAL" => Some(Self::TrustedInternal),
            "TRACE_FORCE_KEEP_DEBUG_TOKEN" => Some(Self::DebugToken),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TraceCandidateDisposition {
    Unspecified = 0,
    Accepted = 1,
    Overloaded = 2,
    Stopped = 3,
}
impl TraceCandidateDisposition {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TRACE_CANDIDATE_DISPOSITION_UNSPECIFIED",
            Self::Accepted => "TRACE_CANDIDATE_DISPOSITION_ACCEPTED",
            Self::Overloaded => "TRACE_CANDIDATE_DISPOSITION_OVERLOADED",
            Self::Stopped => "TRACE_CANDIDATE_DISPOSITION_STOPPED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRACE_CANDIDATE_DISPOSITION_UNSPECIFIED" => Some(Self::Unspecified),
            "TRACE_CANDIDATE_DISPOSITION_ACCEPTED" => Some(Self::Accepted),
            "TRACE_CANDIDATE_DISPOSITION_OVERLOADED" => Some(Self::Overloaded),
            "TRACE_CANDIDATE_DISPOSITION_STOPPED" => Some(Self::Stopped),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeRole {
    Unspecified = 0,
    Standalone = 1,
    Router = 2,
    Ingester = 3,
    Querier = 4,
    Compactor = 5,
    AlertManager = 6,
}
impl NodeRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "NODE_ROLE_UNSPECIFIED",
            Self::Standalone => "NODE_ROLE_STANDALONE",
            Self::Router => "NODE_ROLE_ROUTER",
            Self::Ingester => "NODE_ROLE_INGESTER",
            Self::Querier => "NODE_ROLE_QUERIER",
            Self::Compactor => "NODE_ROLE_COMPACTOR",
            Self::AlertManager => "NODE_ROLE_ALERT_MANAGER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NODE_ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "NODE_ROLE_STANDALONE" => Some(Self::Standalone),
            "NODE_ROLE_ROUTER" => Some(Self::Router),
            "NODE_ROLE_INGESTER" => Some(Self::Ingester),
            "NODE_ROLE_QUERIER" => Some(Self::Querier),
            "NODE_ROLE_COMPACTOR" => Some(Self::Compactor),
            "NODE_ROLE_ALERT_MANAGER" => Some(Self::AlertManager),
            _ => None,
        }
    }
}
include!("cluster.v1.tonic.rs");
// @@protoc_insertion_point(module)