import type * as Monaco from 'monaco-editor/editor/editor.api.js';

type MonacoApi = typeof Monaco;

export const JAVASCRIPT_LANGUAGE_ID = 'javascript';

export const JAVASCRIPT_LANGUAGE_CONFIGURATION: Monaco.languages.LanguageConfiguration = {
  comments: {
    lineComment: '//',
    blockComment: ['/*', '*/'],
  },
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')'],
  ],
  autoClosingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"', notIn: ['string'] },
    { open: "'", close: "'", notIn: ['string', 'comment'] },
    { open: '`', close: '`', notIn: ['string', 'comment'] },
  ],
  surroundingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
    { open: '`', close: '`' },
  ],
};

export const JAVASCRIPT_LANGUAGE: Monaco.languages.IMonarchLanguage = {
  defaultToken: '',
  tokenPostfix: '.js',
  keywords: [
    'async',
    'await',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'debugger',
    'default',
    'delete',
    'do',
    'else',
    'export',
    'extends',
    'false',
    'finally',
    'for',
    'from',
    'function',
    'get',
    'if',
    'import',
    'in',
    'instanceof',
    'let',
    'new',
    'null',
    'of',
    'return',
    'set',
    'static',
    'super',
    'switch',
    'this',
    'throw',
    'true',
    'try',
    'typeof',
    'undefined',
    'var',
    'void',
    'while',
    'with',
    'yield',
  ],
  builtins: [
    'Array',
    'Boolean',
    'Date',
    'Error',
    'JSON',
    'Map',
    'Math',
    'Number',
    'Object',
    'Promise',
    'RegExp',
    'Set',
    'String',
    'Symbol',
    'console',
    'globalThis',
    'molesignal',
  ],
  operators: [
    '<=',
    '>=',
    '==',
    '!=',
    '===',
    '!==',
    '=>',
    '+',
    '-',
    '**',
    '*',
    '/',
    '%',
    '++',
    '--',
    '<<',
    '</',
    '>>',
    '>>>',
    '&',
    '|',
    '^',
    '!',
    '~',
    '&&',
    '||',
    '??',
    '?',
    ':',
    '=',
    '+=',
    '-=',
    '*=',
    '**=',
    '/=',
    '%=',
    '<<=',
    '>>=',
    '>>>=',
    '&=',
    '|=',
    '^=',
    '@',
  ],
  symbols: /[=><!~?:&|+\-*/%^]+/,
  escapes: /\\(?:[abfnrtv\\"'0-9xun]|u\{[0-9A-Fa-f]+\})/,
  tokenizer: {
    root: [
      { include: '@whitespace' },
      [/[{}]/, 'delimiter.bracket'],
      [/[()[\]]/, '@brackets'],
      [/[a-zA-Z_$][\w$]*/, {
        cases: {
          '@keywords': 'keyword',
          '@builtins': 'predefined',
          '@default': 'identifier',
        },
      }],
      [/0[xX][0-9a-fA-F]+n?/, 'number.hex'],
      [/0[bB][01]+n?/, 'number.binary'],
      [/0[oO][0-7]+n?/, 'number.octal'],
      [/(\d*\.)?\d+([eE][+-]?\d+)?n?/, 'number'],
      [/[;,.]/, 'delimiter'],
      [/@symbols/, { cases: { '@operators': 'operator', '@default': '' } }],
      [/"/, 'string', '@stringDouble'],
      [/'/, 'string', '@stringSingle'],
      [/`/, 'string', '@template'],
    ],
    whitespace: [
      [/[ \t\r\n]+/, 'white'],
      [/\/\*/, 'comment', '@comment'],
      [/\/\/.*$/, 'comment'],
    ],
    comment: [
      [/[^/*]+/, 'comment'],
      [/\*\//, 'comment', '@pop'],
      [/[/*]/, 'comment'],
    ],
    stringDouble: [
      [/[^\\"]+/, 'string'],
      [/@escapes/, 'string.escape'],
      [/\\./, 'string.escape.invalid'],
      [/"/, 'string', '@pop'],
    ],
    stringSingle: [
      [/[^\\']+/, 'string'],
      [/@escapes/, 'string.escape'],
      [/\\./, 'string.escape.invalid'],
      [/'/, 'string', '@pop'],
    ],
    template: [
      [/[^\\`$]+/, 'string'],
      [/@escapes/, 'string.escape'],
      [/\\./, 'string.escape.invalid'],
      [/\$\{/, { token: 'delimiter.bracket', next: '@bracketCounting' }],
      [/`/, 'string', '@pop'],
    ],
    bracketCounting: [
      [/\{/, 'delimiter.bracket', '@bracketCounting'],
      [/\}/, 'delimiter.bracket', '@pop'],
      { include: '@root' },
    ],
  },
};

export function registerJavaScriptLanguage(monaco: MonacoApi): void {
  if (!monaco.languages.getLanguages().some(({ id }) => id === JAVASCRIPT_LANGUAGE_ID)) {
    monaco.languages.register({ id: JAVASCRIPT_LANGUAGE_ID });
  }
  monaco.languages.setLanguageConfiguration(
    JAVASCRIPT_LANGUAGE_ID,
    JAVASCRIPT_LANGUAGE_CONFIGURATION,
  );
  monaco.languages.setMonarchTokensProvider(JAVASCRIPT_LANGUAGE_ID, JAVASCRIPT_LANGUAGE);
}
