// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryShardRequest {
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub stream: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub sql: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub time_start_micros: i64,
    #[prost(int64, tag="5")]
    pub time_end_micros: i64,
    /// 本分片需要扫描的 parquet 文件元数据 ID 列表
    #[prost(string, repeated, tag="6")]
    pub file_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// arrow flight ticket 的前缀，便于本分片对应回 FlightService::DoGet 的 ticket
    #[prost(string, tag="7")]
    pub flight_ticket_prefix: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryShardResponse {
    #[prost(bytes="bytes", tag="1")]
    pub arrow_ipc: ::prost::bytes::Bytes,
    #[prost(uint64, tag="2")]
    pub scanned_rows: u64,
    #[prost(string, tag="3")]
    pub flight_ticket: ::prost::alloc::string::String,
}
/// Arrow Flight Ticket 序列化结构：
/// coordinator 切分 parquet_file_metas → 每个 peer 一个 QueryShard → prost::encode_to_vec
/// → arrow_flight::Ticket{ticket: bytes}。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryShard {
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub stream: ::prost::alloc::string::String,
    /// peer 端跑的 SQL（仅 scan + projection + WHERE，跳过最终聚合）
    #[prost(string, tag="3")]
    pub sql: ::prost::alloc::string::String,
    /// 每条对应 parquet_file_meta 行的精简版（避免每次再去 PG 查）。
    ///
    /// 集群内分片：coordinator 预解析并填好这里。
    /// 跨集群联邦（spec federated-search）：coordinator 不知道远端的
    /// parquet_file_meta，故 parquet_file_metas 留空 —— 远端 Flight server 收到空 parquet_file_metas 时
    /// 用 (org_id, stream, stream_type, time_range) 自行 `ParquetFileMetaRepository::find`
    /// 解析本集群的 parquet_file_meta 再扫描。集群内路径永不发空分片，故空＝自解析无歧义。
    #[prost(message, repeated, tag="4")]
    pub parquet_file_metas: ::prost::alloc::vec::Vec<ParquetFileMetaRef>,
    /// SELECT 列投影；空表示 SELECT *
    #[prost(string, repeated, tag="5")]
    pub projection: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag="6")]
    pub time_start_micros: i64,
    #[prost(int64, tag="7")]
    pub time_end_micros: i64,
    /// 联邦自解析所需的 stream 类型（"logs"/"metrics"/"traces"/"extend"）。
    /// 集群内分片可留空（parquet_file_metas 已直接给出对象）。
    #[prost(string, tag="8")]
    pub stream_type: ::prost::alloc::string::String,
    /// 跨集群查询 id（coordinator 下发，远端据此把本地查询登记进可取消表）。
    /// 集群内分片留空。空＝不可经 CancelQuery 远程取消（仍可经 gRPC 流断开兜底）。
    #[prost(string, tag="9")]
    pub federation_query_id: ::prost::alloc::string::String,
}
/// Flight SQL statement ticket（spec flight-sql）：
/// `get_flight_info_statement` 把 {sql, org_id} prost::encode_to_vec 后塞进
/// `TicketStatementQuery.statement_handle`；`do_get` 解出后必须校验 bearer
/// 所属 org 与 ticket org 一致（防跨 org 重放），再交给 QueryService 执行。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FlightSqlTicket {
    #[prost(string, tag="1")]
    pub sql: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParquetFileMetaRef {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub stream: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub stream_type: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub object_key: ::prost::alloc::string::String,
    #[prost(int64, tag="6")]
    pub time_start_micros: i64,
    #[prost(int64, tag="7")]
    pub time_end_micros: i64,
    #[prost(uint64, tag="8")]
    pub rows: u64,
    #[prost(uint64, tag="9")]
    pub size_bytes: u64,
}
include!("query.v1.tonic.rs");
// @@protoc_insertion_point(module)